### ISSUE TITLE
Package installation is not working

### ISSUE THREAD

**Issue by sky-code** [boindil/vue-file-agent-next#7]
**Describe the bug**
Can't install a package with nuxt 3.2.0.

**To Reproduce**
Create a new nuxt project with latest version and run `yarn add @boindil/vue-file-agent-next`.

**Expected behavior**
Package installs correctly.

**Screenshots**
```
yarn add @boindil/vue-file-agent-next 
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning vscode-languageclient@7.0.0: The engine "vscode" appears to be invalid.
error @nuxt/kit@3.0.0-rc.12: The engine "node" is incompatible with this module. Expected version "^14.16.0 || ^16.10.0 || ^17.0.0 || ^18.0.0". Got "19.5.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Additional context**
Probably `@nuxt/kit@3.0.0-rc.12` package needs to be moved into `peerDependencies`

**Comment by boindil** [comment]
Hi @sky-code,
the error message looks to me as if the nuxt version used is incompatible with node 19. I‘ll look into this and will provide a new version probably tomorrow or so.

**Comment by boindil** [comment]
Hi @sky-code 
I'm sorry it took so long - I have some important private stuff going on here.

I've upgraded nuxt/kit to version 3.0.0 - can you confirm this solves the issue? v1.0.5 should work fine.

Please reopen this issue if it does not.

**Comment by sky-code** [comment]
@boindil 
Still seeing the same issue
https://www.npmjs.com/package/@boindil/vue-file-agent-next?activeTab=code
current version on npm specifies `"@nuxt/kit": "3.0.0-rc.12"` as dependency, can you please release next version with fixed dependencies.
